# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  push:
    branches:
      - main
  pull_request:

name: Rust

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install libudev-sys
        run: sudo apt-get install -y libudev-dev

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
